swagger: "2.0"

info:
    title: Questioner API
    version: "0.1"

host: localhost:8080
schemes:
  - http

paths:
    /api/task/{id}:
        get:
            parameters:
              - name: id
                in: path
                type: integer
                format: int64
                required: true
            responses:
                200:
                    description: Task to be worked on
                    schema:
                        $ref: "#/definitions/Task"

definitions:
    Task:
        properties:
            id:
                type: integer
                format: int64
            question:
                type: string
            answers:
                type: array
                items:
                    $ref: "#/definitions/Answer"
                  
    Answer:
        properties:
            id:
                type: integer
                format: int64
            text:
                type: string